name: containerize

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      name:
        type: choice
        required: true
        description: environment for the container image
        options:
        - development
        - staging
        - production
        default: development

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        component: [main]
    env:
      REPO_PREFIX: ghcr.io/${{ github.repository }}/${{ github.events.inputs.environment || 'development' }}/${{ matrix.component }}

    steps:
      - uses: actions/checkout@v4

      - name: login-ghcr
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: build-docker-image
        run: |
          REPO_PREFIX_LOWER=$(echo "$REPO_PREFIX" | tr '[:upper:]' '[:lower:]')
          docker build -t $REPO_PREFIX_LOWER:${{ github.sha }} -f ${{ matrix.component }}/Dockerfile .
          docker push $REPO_PREFIX_LOWER:${{ github.sha }}
          docker tag $REPO_PREFIX_LOWER:${{ github.sha }} $REPO_PREFIX_LOWER:latest
          docker push $REPO_PREFIX_LOWER:latest
